name: Deploy docs

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-docs:
    # Remove the following line if you wish to export your Solidity contracts and interfaces and publish them to NPM
    if: false
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build Docs
        run: yarn docs:build

      - name: Create book folder
        run: mdbook build docs

      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          scope: ${{ secrets.ORG_ID}} #Required
          vercel-args: ${{ github.ref_name == 'main' && '--prod' || '' }}
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          working-directory: ./docs/book
